name: Metrics
on:
  # Schedule updates (every day at 1:30 am UTC)
  schedule: [{cron: "30 1 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_SECRET }}
          plugin_languages: yes
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS" # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_languages_limit: 10                                     # Display up to 8 languages
          plugin_languages_sections: most-used, recently-used           # Display most used and recently used languages stats
          plugin_languages_indepth: no                                  # Get indepth stats (see documentation before enabling)
          plugin_languages_recent_load: 1000                             # Load up to 1000 events to compute recently used stats
          plugin_languages_recent_days: 14                               # Limit recently used stats to last two weeks
          commits_authoring: MrJai@users.noreply.github.com             # Surnames or email addresses used to identify your commits

